import { useState } from "react";
import { ScrollView, Text, View } from "react-native";
import type { ReactElement } from "react";
import { router } from "expo-router";
import { useCreateTopic, useMapQuestions } from "@interestled/api";
import { topicHref } from "@interestled/domain";
import { Button, ErrorState, Input, Sheet } from "@interestled/ui";
import { MapLevels, TimeBudget } from "@interestled/schemas";
import type { MapAnswerT, MapPlanViewT } from "@interestled/schemas";
import { messageOf } from "../../lib/errors";
import { ChipRow } from "../../components/ChipRow";
import { MapQuestions } from "../../components/MapQuestions";

const BUDGETS: { value: TimeBudget; label: string }[] = [
  { value: TimeBudget.Quick, label: "20 minutes" },
  { value: TimeBudget.Week, label: "A week" },
  { value: TimeBudget.Ongoing, label: "Ongoing" },
];

/**
 * How deep the map goes. Two is the default and is named first, because the
 * map's whole job is to be taken in at a glance — a third level buys detail at
 * the cost of the thing the screen exists for, and is only worth it on a subject
 * wide enough that eight groups would not cover it.
 */
const LEVELS: { value: string; label: string; body: string }[] = [
  {
    value: String(MapLevels.Two),
    label: "Two levels",
    body: "Groups, with the nodes you work through inside them. The whole map fits on a screen.",
  },
  {
    value: String(MapLevels.Three),
    label: "Three levels",
    body: "Areas, then groups, then nodes. For a subject too wide to sit under eight headings.",
  },
];

/**
 * The calibration probe. Four questions, under a minute, and it measures rather
 * than asks — where they are now and where they want to get to decides which
 * whole branches get dropped before the learner ever sees them, and where the
 * map is allowed to stop.
 *
 * The two long answers are boxes asking for points rather than one line each:
 * "deploy a service" and "debug it at 3am" are different goals, and a single
 * line quietly asks people to pick one of them.
 *
 * Between the form and the map sit the seven choices. They are the part the form
 * cannot get at: nobody can describe the shape they want a subject cut into, and
 * everybody can pick it out of four.
 */
export default function NewTopicScreen(): ReactElement {
  const create = useCreateTopic();
  const questions = useMapQuestions();
  const [title, setTitle] = useState("");
  const [goal, setGoal] = useState("");
  const [level, setLevel] = useState("");
  const [timeBudget, setTimeBudget] = useState<TimeBudget>(TimeBudget.Week);
  const [levels, setLevels] = useState<MapLevels>(MapLevels.Two);
  // The shape question is asked on the way to generating rather than as a fifth
  // field: it is about the map, not about the learner, and it only matters at
  // the moment the button is pressed.
  const [asking, setAsking] = useState(false);
  // The seven questions, once they have been written. Until then the sheet is
  // still on the level count.
  const [plan, setPlan] = useState<MapPlanViewT | null>(null);

  const input = { title, goal, timeBudget, level, levels, answers: [] };

  const close = (): void => {
    setAsking(false);
    setPlan(null);
  };

  const submit = (answers: MapAnswerT[]): void => {
    create.mutate(
      { ...input, planId: plan?.planId, answers },
      {
        onSuccess: (topic) => {
          close();
          router.replace(topicHref(topic.slug));
        },
      },
    );
  };

  const busy = questions.isPending || create.isPending;

  return (
    <ScrollView contentContainerClassName="gap-5 p-4">
      <Input
        label="What do you want to learn?"
        value={title}
        onChangeText={setTitle}
        placeholder="Kubernetes"
        autoFocus
      />
      <Input
        label="What do you want to be able to do with it? Three points."
        value={goal}
        onChangeText={setGoal}
        multiline
        maxLength={600}
        placeholder={"Deploy a service\nRead the logs when it breaks\nSize it without guessing"}
        hint="This picks the shortest path through the map."
      />
      <Input
        label="Where are you now, and where do you want to get to? 3-5 points."
        value={level}
        onChangeText={setLevel}
        multiline
        maxLength={600}
        placeholder={"I use Docker daily\nNever run anything in production\nWant to own a small cluster"}
        hint="This is the answer that saves you the most time."
      />
      <View className="gap-2">
        <Text className="text-sm font-medium text-ink-soft">How much time have you got?</Text>
        <ChipRow
          options={BUDGETS}
          selected={timeBudget}
          onSelect={(value) => setTimeBudget(value)}
        />
      </View>

      {create.isError ? (
        <ErrorState
          message={messageOf(create.error)}
          hint="The map is generated by the model, so this is usually a key or quota problem."
        />
      ) : null}

      <Button
        label="Build the map"
        onPress={() => setAsking(true)}
        disabled={title.trim().length < 2}
      />

      <Sheet
        visible={asking}
        title={plan === null ? "How deep should the map go?" : "Which of these do you want?"}
        body={
          plan === null
            ? "You can change this later, and rebuild any one group on its own."
            : "Seven choices, and any of them can be skipped."
        }
        onClose={() => (busy ? undefined : close())}
      >
        {plan === null ? (
          <>
            <View className="gap-2">
              <ChipRow
                options={LEVELS.map((option) => ({ value: option.value, label: option.label }))}
                selected={String(levels)}
                onSelect={(value) =>
                  setLevels(value === String(MapLevels.Three) ? MapLevels.Three : MapLevels.Two)
                }
              />
              <Text className="text-sm text-ink-soft">
                {LEVELS.find((option) => option.value === String(levels))?.body ?? ""}
              </Text>
            </View>

            {questions.isError ? <ErrorState message={messageOf(questions.error)} /> : null}

            <Button
              label={questions.isPending ? "Writing the choices…" : "Next"}
              onPress={() => questions.mutate(input, { onSuccess: setPlan })}
              busy={questions.isPending}
            />
            {questions.isPending ? (
              <Text className="text-center text-sm text-ink-faint">
                One model call, usually 10–30 seconds.
              </Text>
            ) : null}
          </>
        ) : (
          <>
            <MapQuestions
              questions={plan.questions}
              finishLabel={create.isPending ? "Building your map…" : "Build the map"}
              busy={create.isPending}
              onFinish={submit}
            />
            {create.isError ? <ErrorState message={messageOf(create.error)} /> : null}
            {create.isPending ? (
              <Text className="text-center text-sm text-ink-faint">
                One model call, usually 10–30 seconds.
              </Text>
            ) : null}
          </>
        )}
      </Sheet>
    </ScrollView>
  );
}
