import { useState } from "react";
import { ScrollView, Text, View } from "react-native";
import type { ReactElement } from "react";
import { router } from "expo-router";
import { useCreateTopic } from "@interestled/api";
import { Button, ErrorState, Input } from "@interestled/ui";
import { TimeBudget } from "@interestled/schemas";
import { messageOf } from "../../lib/errors";
import { ChipRow } from "../../components/ChipRow";

const BUDGETS: { value: TimeBudget; label: string }[] = [
  { value: TimeBudget.Quick, label: "20 minutes" },
  { value: TimeBudget.Week, label: "A week" },
  { value: TimeBudget.Ongoing, label: "Ongoing" },
];

/**
 * The calibration probe. Four questions, under a minute, and it measures rather
 * than asks — "what do you already use" decides which comparisons land and which
 * whole branches get dropped before the learner ever sees them.
 */
export default function NewTopicScreen(): ReactElement {
  const create = useCreateTopic();
  const [title, setTitle] = useState("");
  const [goal, setGoal] = useState("");
  const [known, setKnown] = useState("");
  const [timeBudget, setTimeBudget] = useState<TimeBudget>(TimeBudget.Week);

  const submit = (): void => {
    create.mutate(
      {
        title,
        goal,
        timeBudget,
        knownDomains: known
          .split(",")
          .map((entry) => entry.trim())
          .filter((entry) => entry.length > 0),
      },
      { onSuccess: (topic) => router.replace(`/topic/${topic.id}`) },
    );
  };

  return (
    <ScrollView contentContainerClassName="gap-5 p-4">
      <Input
        label="What do you want to learn?"
        value={title}
        onChangeText={setTitle}
        placeholder="Kubernetes"
        autoFocus
      />
      <Input
        label="What do you want to be able to do with it?"
        value={goal}
        onChangeText={setGoal}
        placeholder="Deploy a service and debug it when it breaks"
        hint="This picks the shortest path through the map."
      />
      <Input
        label="What related things do you already use?"
        value={known}
        onChangeText={setKnown}
        placeholder="docker, linux, ci"
        hint="Comma separated. This is the answer that saves you the most time."
      />
      <View className="gap-2">
        <Text className="text-sm font-medium text-ink-soft">How much time have you got?</Text>
        <ChipRow
          options={BUDGETS}
          selected={timeBudget}
          onSelect={(value) => setTimeBudget(value)}
        />
      </View>

      {create.isError ? (
        <ErrorState
          message={messageOf(create.error)}
          hint="The map is generated by the model, so this is usually a key or quota problem."
        />
      ) : null}

      <Button
        label={create.isPending ? "Building your map…" : "Build the map"}
        onPress={submit}
        busy={create.isPending}
        disabled={title.trim().length < 2}
      />
      {create.isPending ? (
        <Text className="text-center text-sm text-ink-faint">
          One model call, usually 10–30 seconds.
        </Text>
      ) : null}
    </ScrollView>
  );
}
