import { useState } from "react";
import { Text } from "react-native";
import type { ReactElement } from "react";
import { router } from "expo-router";
import { useCreateTopic, useMapQuestions } from "@interestled/api";
import { topicHref } from "@interestled/domain";
import { Button, ErrorState, Screen, Input, Sheet } from "@interestled/ui";
import { MapShapeInput } from "@interestled/schemas";
import type { MapAnswerT, MapPlanViewT, MapShapeT } from "@interestled/schemas";
import { messageOf } from "../../lib/errors";
import { MapQuestions } from "../../components/MapQuestions";
import { MapShapeFields } from "../../components/MapShapeFields";

/**
 * What the settings start at. Parsed out of the input schema rather than written
 * again here, so the screen can never open on a shape a save would not have
 * produced.
 */
const DEFAULT_SHAPE: MapShapeT = MapShapeInput.parse({});

/**
 * Three questions, then the shape of the map.
 *
 * The three are what the map cannot be built without: what to learn, what for,
 * and what they already know. The last is the highest-value answer on the
 * screen — it decides which whole branches are dropped before the learner ever
 * sees them, and two of the generated questions ask about it directly. Both long
 * answers are boxes asking for points rather than one line each, because "deploy
 * a service" and "debug it at 3am" are different answers and a single line
 * quietly asks people to pick one.
 *
 * Where they want to get to used to be half of the third question and is now the
 * depth chip, because "the mechanism underneath" is a thing the map can be built
 * to and a sentence about ambition is not.
 *
 * Between the form and the map sit the seven choices. They are the part no form
 * can get at: nobody can describe the shape they want a subject cut into, and
 * everybody can pick it out of four.
 */
export default function NewTopicScreen(): ReactElement {
  const create = useCreateTopic();
  const questions = useMapQuestions();
  const [title, setTitle] = useState("");
  const [goal, setGoal] = useState("");
  const [level, setLevel] = useState("");
  const [shape, setShape] = useState<MapShapeT>(DEFAULT_SHAPE);
  const [mapInstructions, setMapInstructions] = useState("");
  // The choices are asked on the way to generating rather than as more fields:
  // they are about the map, not about the learner, and they only matter at the
  // moment the button is pressed.
  const [asking, setAsking] = useState(false);
  const [plan, setPlan] = useState<MapPlanViewT | null>(null);

  const input = { title, goal, level, ...shape, mapInstructions, answers: [] };

  const close = (): void => {
    setAsking(false);
    setPlan(null);
  };

  const submit = (answers: MapAnswerT[]): void => {
    create.mutate(
      { ...input, planId: plan?.planId, answers },
      {
        onSuccess: (topic) => {
          close();
          router.replace(topicHref(topic.slug));
        },
      },
    );
  };

  const busy = questions.isPending || create.isPending;

  return (
    <Screen contentContainerClassName="gap-5 p-4">
      <Input
        label="What do you want to learn?"
        value={title}
        onChangeText={setTitle}
        placeholder="Kubernetes"
        autoFocus
      />
      <Input
        label="How do you plan to use this? Two or three points."
        value={goal}
        onChangeText={setGoal}
        multiline
        maxLength={600}
        placeholder={"Deploy a service\nRead the logs when it breaks\nSize it without guessing"}
        hint="This picks the shortest path through the map."
      />
      <Input
        label="What do you already know about it?"
        value={level}
        onChangeText={setLevel}
        multiline
        maxLength={600}
        placeholder={"I use Docker daily\nI have never run anything in production"}
        hint="This is the answer that saves you the most time — it is what gets left out."
      />

      <MapShapeFields
        shape={shape}
        onShape={setShape}
        instructions={mapInstructions}
        onInstructions={setMapInstructions}
      />

      {create.isError ? (
        <ErrorState
          message={messageOf(create.error)}
          hint="The map is generated by the model, so this is usually a key or quota problem."
        />
      ) : null}

      <Button
        label="Build the map"
        onPress={() => setAsking(true)}
        disabled={title.trim().length < 2}
      />

      <Sheet
        visible={asking}
        title={plan === null ? "Ready to build it?" : "Which of these do you want?"}
        body={
          plan === null
            ? "Seven quick choices first. You can rebuild any one group later on its own."
            : "Seven choices, and any of them can be skipped."
        }
        onClose={() => (busy ? undefined : close())}
      >
        {plan === null ? (
          <>
            {questions.isError ? <ErrorState message={messageOf(questions.error)} /> : null}

            <Button
              label={questions.isPending ? "Writing the choices…" : "Next"}
              onPress={() => questions.mutate(input, { onSuccess: setPlan })}
              busy={questions.isPending}
            />
            {questions.isPending ? (
              <Text className="text-center text-sm text-ink-faint">
                One model call, usually 10–30 seconds.
              </Text>
            ) : null}
          </>
        ) : (
          <>
            <MapQuestions
              questions={plan.questions}
              finishLabel={create.isPending ? "Building your map…" : "Build the map"}
              busy={create.isPending}
              onFinish={submit}
            />
            {create.isError ? <ErrorState message={messageOf(create.error)} /> : null}
            {create.isPending ? (
              <Text className="text-center text-sm text-ink-faint">
                One model call, usually 10–30 seconds.
              </Text>
            ) : null}
          </>
        )}
      </Sheet>
    </Screen>
  );
}
